name: timesketch-dev

networks:
  timesketch-dev:

services:
  timesketch:
    image: us-docker.pkg.dev/osdfir-registry/timesketch/dev:latest
    command: timesketch
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8080:8080"
    environment:
      POSTGRES_USER: "timesketch"
      POSTGRES_PASSWORD: "password"
      POSTGRES_ADDRESS: "postgres"
      POSTGRES_PORT: "5432"
      OPENSEARCH_HOST: "opensearch"
      OPENSEARCH_PORT: "9200"
      REDIS_ADDRESS: "redis"
      REDIS_PORT: "6379"
      TIMESKETCH_USER: "dev"
      TIMESKETCH_PASSWORD: "dev"
      CHOKIDAR_USEPOLLING: "true"
      prometheus_multiproc_dir: "/tmp/"
    volumes:
      - "../../:/usr/local/src/timesketch/"
    depends_on:
      - opensearch
      - postgres
      - redis
    networks:
      - timesketch-dev

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    environment:
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      network.host: "0.0.0.0"
      OPENSEARCH_JAVA_OPTS: "-Xms2g -Xmx2g"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      DISABLE_SECURITY_PLUGIN: "true" # TODO: Enable when we have migrated the python client to Opensearch as well.
    ports:
      - "9200:9200"
    networks:
      - timesketch-dev
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: "timesketch"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - timesketch-dev

  redis:
    image: redis:6.0.10-alpine
    ports:
      - "6379:6379"
    networks:
      - timesketch-dev

  notebook:
    image: us-docker.pkg.dev/osdfir-registry/timesketch/notebook:latest
    ports:
      - "8844:8844"
    volumes:
      - "../../:/usr/local/src/timesketch/:ro"
      - "/tmp/:/usr/local/src/picadata/"
    depends_on:
      - opensearch
    networks:
      - timesketch-dev

  prometheus:
    image: prom/prometheus:v2.24.1
    volumes:
      - "./prometheus:/etc/prometheus:ro"
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - timesketch
    networks:
      - timesketch-dev
