services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:0.100.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
    depends_on:
      - jaeger

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "127.0.0.1:16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

networks:
  default:
    name: timesketch-network
    external: true
