{{- if .Values.ingress.enabled -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: timesketch-loadbalancer-frontend-config
  namespace: timesketch
spec:
  redirectToHttps:
    enabled: true
{{- end }}