#!/bin/bash
#
# Script to set up Travis-CI test VM.
#
# This file is generated by l2tdevtools update-dependencies.py any dependency
# related changes should be made in dependencies.ini.

# Exit on error.
set -e;
if test ${TRAVIS_OS_NAME} = "linux" && test ${TARGET} != "jenkins";
then
	if test ${TARGET} = "pylint";
	then
		sudo add-apt-repository ppa:gift/pylint3 -y;
	fi

	sudo apt-get update -q;

	if test ${TARGET} = "pylint";
	then
		sudo apt-get install -y pylint;
	fi
fi
