#!/bin/bash
#
# Script to run Python 2 tests on Travis-CI.
#
# This file is generated by l2tdevtools update-dependencies.py, any dependency
# related changes should be made in dependencies.ini.

# Exit on error.
set -e;

nosetests

python2 ./setup.py build

python2 ./setup.py sdist

python2 ./setup.py bdist
