#!/bin/bash
#
# Script to run Python 3 tests on Travis-CI.
#
# This file is generated by l2tdevtools update-dependencies.py, any dependency
# related changes should be made in dependencies.ini.

# Exit on error.
set -e;

nosetests3

python3 ./setup.py build

python3 ./setup.py sdist

python3 ./setup.py bdist
