timesketch:
    build: .
    ports:
        - "5000"
    links:
        - elasticsearch
        - postgres
    restart: always
elasticsearch:
    image: elasticsearch
    ports:
        - "9200"
        - "9300"
    restart: always
postgres:
    image: postgres
    ports:
        - "5432"
    restart: always
