timesketch:
    build: .
    ports:
        - "5000:5000"
    links:
        - elasticsearch
        - postgres
        - redis
    environment:
        - POSTGRES_USER=timesketch
        - POSTGRES_PASSWORD=timesketch
        - POSTGRES_ADDRESS=postgres # Use hostname linking
        - POSTGRES_PORT=5432
        - ELASTIC_ADDRESS=elastic # Use hostname linking
        - ELASTIC_PORT=9200
        - TIMESKETCH_USER=admin
        - TIMESKETCH_PASSWORD=password
        - CELERY_BROKER=redis # Use hostname linking
    restart: always
elasticsearch:
    image: elasticsearch:2.4.1
    command: elasticsearch -Des.node.name="TimesketchNode" -Des.script.groovy.sandbox.enabled=true
    ports: # Expose ports for debugging and manual database management
        - "9200:9200"
        - "9300:9300"
    restart: always
postgres:
    image: postgres:9.3.14
    ports: # Expose ports for debugging and manual database management
        - "5432:5432"
    environment:
        - POSTGRES_USER=timesketch
        - POSTGRES_PASSWORD=timesketch
    restart: always
redis:
    image: redis
    ports:
        - "6379:6379"
    restart: always

