version: "3"
services:
  timesketch:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
      - postgres
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
      - POSTGRES_ADDRESS=postgres
      - POSTGRES_PORT=5432
      - ELASTIC_ADDRESS=elasticsearch
      - ELASTIC_PORT=9200
    restart: always
  elasticsearch:
    image: elasticsearch:2.4
    restart: always
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
    restart: always
