timesketch:
    build: .
    ports:
        - "5000"
    links:
        - elasticsearch
        - postgres
elasticsearch:
    image: elasticsearch:2.4.1
    command: elasticsearch -Des.node.name="TimesketchNode"
    volumes:
        - ./cache:/tmp/cache
    ports:
        - "9200"
        - "9300"
postgres:
    image: postgres:9.3.14
    ports:
        - "5432"
    environment:
        - POSTGRES_USER=timesketch
        - POSTGRES_PASSWORD=timesketch
