# -*- mode: ruby -*-
# vi: set ft=ruby :

# Set VirtualBox as default provider
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = true

  # Forward the default Timesketch webserver port
  config.vm.network :forwarded_port, guest: 5000, host: 5000

  # Access to Elasticsearch
  config.vm.network :forwarded_port, guest: 9200, host: 9200

  # Share folder to the guest VM
  config.vm.synced_folder "../", "/usr/local/src/timesketch"

  # VirtualBox configuration
  config.vm.provider "virtualbox" do |vb|
    vb.name = "timesketch-dev"
    vb.cpus = 2
    vb.memory = 4096
  end

  # Setup the system with a shell script
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.hostname = "timesketch-dev"
end
