# -*- mode: ruby -*-
# vi: set ft=ruby :

# Set VirtualBox as default provider
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

unless Vagrant.has_plugin?("vagrant-disksize")
  raise 'vagrant-disksize is not installed ("vagrant plugin install vagrant-disksize")'
end

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.disksize.size = "50GB"
  config.vm.box_check_update = true

  # Access to Timesketch from the host
  config.vm.network :forwarded_port, guest: 5000, host: 5000
  config.vm.network :forwarded_port, guest: 9200, host: 9200

  # Access to Timesketch from the host
  config.vm.network :forwarded_port, guest: 9200, host: 9200

  # Access to Neo4j from the host
  config.vm.network :forwarded_port, guest: 7474, host: 7474
  config.vm.network :forwarded_port, guest: 7687, host: 7687

  # Share folder to the guest VM
  config.vm.synced_folder "../", "/usr/local/src/timesketch"

  # VirtualBox configuration
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end

  # Setup the system with a shell script
  config.vm.provision :shell, keep_color: true, path: "bootstrap.sh"
  config.vm.hostname = "timesketch-dev"
end
