apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesketch-worker
  namespace: timesketch
  labels:
    app: timesketch-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timesketch-worker
  template:
    metadata:
      annotations:
        prometheus.io/port: "9200"
        prometheus.io/scrape: "true"
      labels:
        app: timesketch-worker
    spec:
      serviceAccountName: timesketch
      containers:
        - name: timesketch-worker
          image: us-docker.pkg.dev/osdfir-registry/timesketch/timesketch:latest
          command: ["sh", "-c", "./docker-entrypoint.sh timesketch-worker"]
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
                apiVersion: v1
          - name: WORKER_LOG_LEVEL
            value: 'DEBUG'
          volumeMounts:
            - mountPath: /mnt/timesketchvolume
              name: timesketchvolume
            - mountPath: /var/log/timesketch
              name: timesketchvolume
              subPathExpr: logs/$(POD_NAME)
            - mountPath: /etc/timesketch/
              name: timesketch-conf
          ports:
            - containerPort: 5000 
          resources: 
            requests:
              cpu: 2000m
              memory: 4000Mi
            limits:
              cpu: 8000m
              memory: 16000Mi
      volumes:
        - name: timesketchvolume
          persistentVolumeClaim:
            claimName: timesketchvolume-claim
            readOnly: false
        - name: timesketch-conf
          configMap:
            name: timesketch-config