{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "timesketch.fullname" . }}-worker-metrics
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: worker
    {{- include "timesketch.selectorLabels" . | nindent 4 }}
{{- end }}