<!--
Copyright 2025 Google Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<template>
  <v-card
    color="transparent"
    elevation="0"
    :class="['mt-1 mb-6 d-flex align-center justify-space-between', isCompact ? 'actions--compact' : '']"
  >
    <v-card-item v-if="isCompact">
      <v-btn size="small" variant="text" color="primary" @click="store.setActiveQuestion(question)"
        >View Result Details <v-icon icon="mdi-arrow-right" class="ml-2" small
      /></v-btn>
    </v-card-item>

    <div v-if="!isCompact" class="actions__item-group">
      <div class="actions__item">
        <QuestionPrioritySelect :question="question" />
      </div>

      <div class="actions__item">
        <v-chip
          :title="questionStatus"
          :prepend-icon="statusIcon"
          :class="['question-status-chip', `question-status-chip--${questionStatus}`]"
        >
          {{ questionStatus.replace(/-/g, ' ') }}
        </v-chip>
      </div>

      <div class="actions__item">
        <div class="question-status-chip__group" v-if="!question.user?.name">
          <CreationIcon :width="28" :height="28" />
          <v-chip title="Generated by AI" :class="['question-status-chip', `question-status-chip--ai`]" size="small">
            Generated by AI
          </v-chip>
        </div>
      </div>
    </div>

    <v-card-actions v-if="!isApproved && !isRejected" class="pa-0">
      <v-btn
        :disabled="reportLocked"
        @click="rejectQuestion(question.id)"
        color="primary"
        size="small"
        title="Mark this question as not relevant"
        :class="!isCompact ? 'actions__btn--large' : 'px-4'"
        >mark as not relevant</v-btn
      >
      <v-btn
        variant="flat"
        color="primary"
        @click="confirmAndSave()"
        :disabled="reportLocked"
        size="small"
        :class="!isCompact ? 'action-btn--large' : 'px-4'"
      >
        Verify Question
      </v-btn>
    </v-card-actions>
    <v-card-actions v-else class="pa-0">
       <v-btn
        variant="text"
        color="primary"
        @click="reopenConfirmationDialog = true"
        :disabled="reportLocked"
        size="small"
        :class="!isCompact ? 'action-btn--large' : 'px-4'"
        prepend-icon="mdi-pencil-outline"
      >
        Re-open for Review
      </v-btn>
    </v-card-actions>

    <!-- Re-open confirmation dialog -->
    <v-dialog v-model="reopenConfirmationDialog" max-width="500">
      <v-card>
        <v-card-title>
          <v-icon color="warning" class="mr-2">mdi-alert-circle-outline</v-icon>
          {{ reopenDialogTitle }}
        </v-card-title>
        <v-card-text>
          {{ reopenDialogText }}
        </v-card-text>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn text @click="reopenConfirmationDialog = false">Cancel</v-btn>
          <v-btn color="primary" text @click="confirmReopen">Yes, Re-open</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-card>
</template>

<script>
import { useAppStore } from '@/stores/app'
import RestApiClient from '@/utils/RestApiClient'
import QuestionPrioritySelect from './QuestionPrioritySelect.vue'
import { getPriorityFromLabels } from '@/components/AiInvestigationCanvas/_utils/QuestionPriority.js'

export default {
  components: {
    QuestionPrioritySelect,
  },
  inject: ['updateQuestion'],
  props: {
    question: Object,
    index: Number,
    reportLocked: Boolean,
    isApproved: Boolean,
    variant: String,
  },
  data() {
    return {
      store: useAppStore(),
      isSubmitting: false,
      reopenConfirmationDialog: false,
    }
  },
  computed: {
    reopenDialogTitle() {
      if (this.isRejected) {
        return 'Restore Rejected Question?'
      }
      return 'Re-open Question?'
    },
    reopenDialogText() {
      if (this.isRejected) {
        return "This action will remove the 'rejected' status and set the question back to 'pending-review'. It will reappear in the main list and can be worked on again. Are you sure you want to proceed?"
      }
      return "This question was already marked as answered by an analyst. This action will re-open the question as 'pending-review', allowing its answer and conclusions to be edited again. Are you sure you want to proceed?"
    },
    isCompact() {
      return this.variant === 'compact'
    },
    isRejected() {
      return this.question?.status?.status === 'rejected'
    },
    priority() {
      return getPriorityFromLabels(this.question.labels)
    },
    questionStatus() {
      return this.question?.status?.status || 'new'
    },
    statusIcon() {
      switch (this.questionStatus) {
        case 'verified':
          return 'mdi-check-circle-outline'
        case 'rejected':
          return 'mdi-close'
        case 'pending-review':
          return 'mdi-magnify'
        case 'new':
          return 'mdi-star-outline'
        default:
          return 'mdi-help-circle-outline'
      }
    },
  },
  methods: {
    async updateQuestionStatus(questionId, status) {
      if (this.isSubmitting) return
      this.isSubmitting = true

      let notificationDetails = {}
      switch (status) {
        case 'verified':
          notificationDetails = {
            statusText: 'verified',
            errorText: 'verify',
            icon: 'mdi-check-circle-outline',
            type: 'success',
          }
          break
        case 'rejected':
          notificationDetails = {
            statusText: 'rejected',
            errorText: 'reject',
            icon: 'mdi-minus-circle-outline',
            type: 'success',
          }
          break
        case 'pending-review':
          notificationDetails = {
            statusText: 're-opened for review',
            errorText: 're-open',
            icon: 'mdi-pencil-outline',
            type: 'info',
          }
          break
        default:
          notificationDetails = {
            statusText: `set to ${status}`,
            errorText: 'update',
            icon: 'mdi-information-outline',
            type: 'info',
          }
      }

      try {
        // Update the question status
        await RestApiClient.updateQuestion(this.store.sketch.id, questionId, {
          status: status,
        })

        // Rerender with updated status
        const updatedQuestion = await RestApiClient.getQuestion(this.store.sketch.id, questionId)
        const newQuestionData = updatedQuestion.data.objects[0]

        // Update the question in the main list
        this.updateQuestion(newQuestionData)

        // Handle the active view based on the new status
        if (status === 'pending-review') {
          // If re-opened, update the active question view with the new data
          this.store.setActiveQuestion(newQuestionData)
        } else {
          // For other statuses, close the detailed view
          this.store.setActiveQuestion(null)
        }

        this.store.setNotification({
          text: this.index
            ? `Question ${this.index + 1} has been ${notificationDetails.statusText}`
            : `This question has been ${notificationDetails.statusText}`,
          icon: notificationDetails.icon,
          type: notificationDetails.type,
        })
      } catch (error) {
        console.error(error)
        this.store.setNotification({
          text: `Unable to ${notificationDetails.errorText} question. Please try again.`,
          icon: 'mdi-alert-circle-outline',
          type: 'error',
        })
      } finally {
        this.isSubmitting = false
      }
    },
    async confirmAndSave() {
      await this.updateQuestionStatus(this.question.id, 'verified')
    },
    async rejectQuestion() {
      await this.updateQuestionStatus(this.question.id, 'rejected')
    },
    async confirmReopen() {
      this.reopenConfirmationDialog = false;
      await this.updateQuestionStatus(this.question.id, 'pending-review');
    },
  },
}
</script>

<style scoped>
.actions--compact {
  border-radius: 8px;
  border: 1px solid var(--theme-ai-color-gray-100);
  background-color: var(--theme-ai-color-gray-50) !important;
  padding: 0 24px;

  &:deep(.v-card-item) {
    padding: 0;
  }
}

.actions__btn--large {
  height: 40px;
  border-radius: 8px !important;
  padding: 0 20px;
}

.actions__item-group {
  display: flex;
  flex-wrap: nowrap;
  gap: 8px;
}
</style>
