<!--
Copyright 2025 Google Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<template>
  <v-card
    color="transparent"
    elevation="0"
    :class="['mt-1 mb-6 d-flex align-center justify-space-between', isCompact ? 'actions--compact' : '']"
  >
    <v-card-item v-if="isCompact">
      <v-btn size="small" variant="text" color="primary" @click="store.setActiveQuestion(question)"
        >View Result Details <v-icon icon="mdi-arrow-right" class="ml-2" small
      /></v-btn>

      <!-- <p v-else class="font-weight-medium mb-1">
        Would you like to save the results to the report?
      </p> -->
    </v-card-item>

    <div v-if="!isCompact" class="actions__item-group">
      <div class="actions__item">
        <QuestionPrioritySelect :question="question" />
      </div>

      <div class="actions__item">
        <v-chip
          :title="questionStatus"
          :prepend-icon="statusIcon"
          :class="['question-status-chip', `question-status-chip--${questionStatus}`]"
        >
          {{ questionStatus.replace(/-/g, ' ') }}
        </v-chip>
      </div>

      <div class="actions__item">
        <div class="question-status-chip__group" v-if="!question.user?.name">
          <CreationIcon :width="28" :height="28" />
          <v-chip title="Generated by AI" :class="['question-status-chip', `question-status-chip--ai`]" size="small">
            Generated by AI
          </v-chip>
        </div>
      </div>
    </div>

    <v-card-actions class="pa-0">
      <v-btn
        :disabled="reportLocked || isRejected"
        @click="rejectQuestion(question.id)"
        color="primary"
        size="small"
        title="Mark this question as not relevant"
        :class="!isCompact ? 'actions__btn--large' : 'px-4'"
        >mark as not relevant</v-btn
      >
      <v-btn
        variant="flat"
        color="primary"
        @click="confirmAndSave()"
        :disabled="reportLocked || isApproved"
        size="small"
        :class="!isCompact ? 'action-btn--large' : 'px-4'"
      >
        Verify Question
      </v-btn>
    </v-card-actions>
  </v-card>
</template>

<script>
import { useAppStore } from '@/stores/app'
import RestApiClient from '@/utils/RestApiClient'
import QuestionPrioritySelect from './QuestionPrioritySelect.vue'
import { getPriorityFromLabels } from '@/components/AiInvestigationCanvas/_utils/QuestionPriority.js'

export default {
  components: {
    QuestionPrioritySelect,
  },
  inject: ['updateQuestion'],
  props: {
    question: Object,
    index: Number,
    reportLocked: Boolean,
    isApproved: Boolean,
    variant: String,
  },
  data() {
    return {
      store: useAppStore(),
      isSubmitting: false,
      isConfirming: false,
    }
  },
  computed: {
    isCompact() {
      return this.variant === 'compact'
    },
    isRejected() {
      return this.question?.status?.status === 'rejected'
    },
    priority() {
      return getPriorityFromLabels(this.question.labels)
    },
    questionStatus() {
      return this.question?.status?.status || 'new'
    },
    statusIcon() {
      switch (this.questionStatus) {
        case 'verified':
          return 'mdi-check-circle-outline'
        case 'rejected':
          return 'mdi-close'
        case 'pending-review':
          return 'mdi-magnify'
        case 'new':
          return 'mdi-star-outline'
        default:
          return 'mdi-help-circle-outline'
      }
    },
  },
  methods: {
    async updateQuestionStatus(questionId, status) {
      const isSubmitting = status === 'rejected' ? 'isSubmitting' : 'isConfirming'
      const statusText = status === 'verified' ? 'verified' : 'rejected'
      const errorText = status === 'verified' ? 'verify' : 'reject'
      const icon = status === 'verified' ? 'mdi-check-circle-outline' : 'mdi-minus-circle-outline'

      try {
        this[isSubmitting] = true

        // Update the question status
        await RestApiClient.updateQuestion(this.store.sketch.id, questionId, {
          status: status,
        })

        // Rerender with updated status
        const updatedQuestion = await RestApiClient.getQuestion(this.store.sketch.id, questionId)

        // Update the question in the store
        this.updateQuestion(updatedQuestion.data.objects[0])

        this.store.setActiveQuestion(null)

        this.store.setNotification({
          text: this.index
            ? `Question ${this.index + 1} has been ${statusText}`
            : `This question has been ${statusText}`,
          icon: icon,
          type: 'success',
        })
      } catch (error) {
        console.error(error)
        this.store.setNotification({
          text: `Unable to ${errorText} question. Please try again.`,
          icon: 'mdi-alert-circle-outline',
          type: 'error',
        })
      } finally {
        this[isSubmitting] = false
      }
    },
    async confirmAndSave() {
      await this.updateQuestionStatus(this.question.id, 'verified')
    },
    async rejectQuestion() {
      await this.updateQuestionStatus(this.question.id, 'rejected')
    },
  },
}
</script>

<style scoped>
.actions--compact {
  border-radius: 8px;
  border: 1px solid var(--theme-ai-color-gray-100);
  background-color: var(--theme-ai-color-gray-50) !important;
  padding: 0 24px;

  &:deep(.v-card-item) {
    padding: 0;
  }
}

.actions__btn--large {
  height: 40px;
  border-radius: 8px !important;
  padding: 0 20px;
}

.actions__item-group {
  display: flex;
  flex-wrap: nowrap;
  gap: 8px;
}
</style>
