{{- $userconfigs := .Files.Glob .Values.config.override }}
{{- if $userconfigs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timesketch.fullname" . }}-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
data:
{{ ($userconfigs).AsConfig | indent 2 }}
{{- end }}