apiVersion: v1
kind: Secret
metadata:
  name: {{ template "timesketch.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
data:
  timesketch-secret: {{ randAlphaNum 32 | b64enc | quote }}