apiVersion: v1
kind: Service
metadata:
  name: {{ include "timesketch.fullname" . }}-svc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
  {{- if .Values.ingress.enabled }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"5000":"timesketch-neg-healthcheck"}}'
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/component: frontend
    {{- include "timesketch.selectorLabels" . | nindent 4 }}