apiVersion: v1
kind: Service
metadata:
  name: timesketch-web
  namespace: timesketch
  labels:
    app: timesketch-web
  annotations:
    {{- if .Values.ingress.enabled }}
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"5000":"timesketch-neg-healthcheck"}}'
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: timesketch-web
