apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "timesketch.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: frontend
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      {{- include "timesketch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.metrics.enabled }} 
      annotations:
        prometheus.io/port: {{ .Values.metrics.port | quote }}
        prometheus.io/scrape: "true"
      {{- end }}
      labels:
        app.kubernetes.io/component: frontend
        {{- include "timesketch.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "timesketch.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-timesketch
          image: busybox
          command: ['sh', '-c', '/init/init-timesketch.sh']
          env:
            {{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                # Referencing from charts/redis/templates/_helpers.tpl
                secretKeyRef:
                  name: {{ include "redis.secretName" .Subcharts.redis }}
                  key: {{ include "redis.secretPasswordKey" .Subcharts.redis }}
            {{- end }}
            {{- if .Values.postgresql.enabled }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                # Referencing from charts/postgresql/templates/_helpers.tpl
                secretKeyRef:
                  name: {{ include "postgresql.secretName" .Subcharts.postgresql }}
                  key: {{ include "postgresql.adminPasswordKey" .Subcharts.postgresql }}
            {{- end }}
          volumeMounts:
            - mountPath: /init
              name: init-timesketch
            - mountPath: /etc/timesketch
              name: timesketchvolume
              subPath: configs
      containers:
        - name: frontend
          securityContext:
              {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "./docker-entrypoint.sh timesketch-web"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
                  apiVersion: v1
          volumeMounts:
            - mountPath: {{ (include "timesketch.uploadPath" .) | quote }}
              name: timesketchvolume
              subPath: uploads
            - mountPath: /var/log/timesketch
              name: timesketchvolume
              subPathExpr: logs/$(POD_NAME)
            - mountPath: /etc/timesketch
              name: timesketchvolume
              subPath: configs
          ports:
            {{- if .Values.metrics.enabled }}
            - containerPort: {{ .Values.metrics.port }}
            {{- end }}
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      volumes:
        - name: timesketchvolume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name }}-claim
            readOnly: false
        - name: init-timesketch
          configMap:
            name: {{ include "timesketch.fullname" . }}-init-configmap
            defaultMode: 0744
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
