apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "timesketch.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: worker
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      {{- include "timesketch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: worker
        {{- include "timesketch.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "timesketch.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "./docker-entrypoint.sh timesketch-worker"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
                  apiVersion: v1
          volumeMounts:
            - mountPath: /mnt/timesketchvolume
              name: timesketchvolume
            - mountPath: /var/log/timesketch
              name: timesketchvolume
              subPathExpr: logs/$(POD_NAME)
            - mountPath: /etc/timesketch/
              name: timesketch-conf
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}
      volumes:
        - name: timesketchvolume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name }}-claim
            readOnly: false
        - name: timesketch-conf
          configMap:
            name: timesketch-config
