apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "timesketch.fullname" . }}-worker
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: worker
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      {{- include "timesketch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: worker
        {{- include "timesketch.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "timesketch.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "./docker-entrypoint.sh timesketch-worker"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
                  apiVersion: v1
            - name: WORKER_LOG_LEVEL
              value: "DEBUG"
          volumeMounts:
            - mountPath: {{ .Values.persistence.mountPath }}
              name: timesketchvolume
            - mountPath: /var/log/timesketch
              name: timesketchvolume
              subPathExpr: logs/$(POD_NAME)
            - mountPath: /etc/timesketch
              name: timesketchvolume
              subPath: configs
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}
      volumes:
        - name: timesketchvolume
          persistentVolumeClaim:
            claimName: {{ include "timesketch.pvc.name"  . }}
            readOnly: false
        - name: timesketch-init
          configMap:
            name: {{ include "timesketch.fullname" . }}-init-configmap
            defaultMode: 0744
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

