# Copyright 2018 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Emoji codepoint definitions.

See https://emojipedia.org for list of available unicode emojis.
"""

from __future__ import unicode_literals

import collections


emoji = collections.namedtuple('emoji', 'code help')


EMOJI_MAP = {
    'BUCKET': emoji('&#x1FAA3', 'Storage bucket'),
    'CAMERA': emoji('&#x1F4F7', 'Screenshot activity'),
    'FISHING_POLE': emoji('&#x1F3A3', 'Phishing'),
    'GLOBE': emoji('&#x1F30F', 'The world'),
    'ID_BUTTON': emoji('&#x1F194', 'Account ID'),
    'LINK': emoji('&#x1F517', 'Events Linked'),
    'LOCK': emoji('&#x1F512', 'Logon activity'),
    'LOCOMOTIVE': emoji('&#x1F682', 'Execution activity'),
    'MAGNIFYING_GLASS': emoji('&#x1F50E', 'Search related activity'),
    'PERSON_STANDING': emoji('&#x1F9CD', 'Person'),
    'SATELLITE': emoji('&#x1F4E1', 'Domain activity'),
    'SCREEN': emoji('&#x1F5B5', 'Screensaver activity'),
    'SKULL': emoji('&#x1F480;', 'Threat intel match'),
    'SKULL_CROSSBONE': emoji('&#x2620', 'Suspicious entry'),
    'SLEEPING_FACE': emoji('&#x1F634', 'Activity outside of regular hours'),
    'SPARKLES': emoji('&#x2728', 'New entity created'),
    'UNLOCK': emoji('&#x1F513', 'Logoff activity'),
    'WASTEBASKET': emoji('&#x1F5D1', 'Deletion activity'),
    'FLAC_AC': emoji('&#x1F1E6&#x1F1E8', 'Ascension Island'),
    'FLAC_AD': emoji('&#x1F1E6&#x1F1E9', 'Andorra'),
    'FLAC_AE': emoji('&#x1F1E6&#x1F1EA', 'United Arab Emirates'),
    'FLAC_AF': emoji('&#x1F1E6&#x1F1EB', 'Afghanistan'),
    'FLAC_AG': emoji('&#x1F1E6&#x1F1EC', 'Antigua & Barbuda'),
    'FLAC_AI': emoji('&#x1F1E6&#x1F1EE', 'Anguilla'),
    'FLAC_AL': emoji('&#x1F1E6&#x1F1F1', 'Albania'),
    'FLAC_AM': emoji('&#x1F1E6&#x1F1F2', 'Armenia'),
    'FLAC_AO': emoji('&#x1F1E6&#x1F1F4', 'Angola'),
    'FLAC_AQ': emoji('&#x1F1E6&#x1F1F6', 'Antarctica'),
    'FLAC_AR': emoji('&#x1F1E6&#x1F1F7', 'Argentina'),
    'FLAC_AS': emoji('&#x1F1E6&#x1F1F8', 'American Samoa'),
    'FLAC_AT': emoji('&#x1F1E6&#x1F1F9', 'Austria'),
    'FLAC_AU': emoji('&#x1F1E6&#x1F1FA', 'Australia'),
    'FLAC_AW': emoji('&#x1F1E6&#x1F1FC', 'Aruba'),
    'FLAC_AX': emoji('&#x1F1E6&#x1F1FD', 'Åland Islands'),
    'FLAC_AZ': emoji('&#x1F1E6&#x1F1FF', 'Azerbaijan'),
    'FLAC_BA': emoji('&#x1F1E7&#x1F1E6', 'Bosnia & Herzegovina'),
    'FLAC_BB': emoji('&#x1F1E7&#x1F1E7', 'Barbados'),
    'FLAC_BD': emoji('&#x1F1E7&#x1F1E9', 'Bangladesh'),
    'FLAC_BE': emoji('&#x1F1E7&#x1F1EA', 'Belgium'),
    'FLAC_BF': emoji('&#x1F1E7&#x1F1EB', 'Burkina Faso'),
    'FLAC_BG': emoji('&#x1F1E7&#x1F1EC', 'Bulgaria'),
    'FLAC_BH': emoji('&#x1F1E7&#x1F1ED', 'Bahrain'),
    'FLAC_BI': emoji('&#x1F1E7&#x1F1EE', 'Burundi'),
    'FLAC_BJ': emoji('&#x1F1E7&#x1F1EF', 'Benin'),
    'FLAC_BL': emoji('&#x1F1E7&#x1F1F1', 'St. Barthélemy'),
    'FLAC_BM': emoji('&#x1F1E7&#x1F1F2', 'Bermuda'),
    'FLAC_BN': emoji('&#x1F1E7&#x1F1F3', 'Brunei'),
    'FLAC_BO': emoji('&#x1F1E7&#x1F1F4', 'Bolivia'),
    'FLAC_BQ': emoji('&#x1F1E7&#x1F1F6', 'Caribbean Netherlands'),
    'FLAC_BR': emoji('&#x1F1E7&#x1F1F7', 'Brazil'),
    'FLAC_BS': emoji('&#x1F1E7&#x1F1F8', 'Bahamas'),
    'FLAC_BT': emoji('&#x1F1E7&#x1F1F9', 'Bhutan'),
    'FLAC_BV': emoji('&#x1F1E7&#x1F1FB', 'Bouvet Island'),
    'FLAC_BW': emoji('&#x1F1E7&#x1F1FC', 'Botswana'),
    'FLAC_BY': emoji('&#x1F1E7&#x1F1FE', 'Belarus'),
    'FLAC_BZ': emoji('&#x1F1E7&#x1F1FF', 'Belize'),
    'FLAC_CA': emoji('&#x1F1E8&#x1F1E6', 'Canada'),
    'FLAC_CC': emoji('&#x1F1E8&#x1F1E8', 'Cocos (Keeling) Islands'),
    'FLAC_CD': emoji('&#x1F1E8&#x1F1E9', 'Congo - Kinshasa'),
    'FLAC_CF': emoji('&#x1F1E8&#x1F1EB', 'Central African Republic'),
    'FLAC_CG': emoji('&#x1F1E8&#x1F1EC', 'Congo - Brazzaville'),
    'FLAC_CH': emoji('&#x1F1E8&#x1F1ED', 'Switzerland'),
    'FLAC_CI': emoji('&#x1F1E8&#x1F1EE', 'Côte d’Ivoire'),
    'FLAC_CK': emoji('&#x1F1E8&#x1F1F0', 'Cook Islands'),
    'FLAC_CL': emoji('&#x1F1E8&#x1F1F1', 'Chile'),
    'FLAC_CM': emoji('&#x1F1E8&#x1F1F2', 'Cameroon'),
    'FLAC_CN': emoji('&#x1F1E8&#x1F1F3', 'China'),
    'FLAC_CO': emoji('&#x1F1E8&#x1F1F4', 'Colombia'),
    'FLAC_CP': emoji('&#x1F1E8&#x1F1F5', 'Clipperton Island'),
    'FLAC_CR': emoji('&#x1F1E8&#x1F1F7', 'Costa Rica'),
    'FLAC_CU': emoji('&#x1F1E8&#x1F1FA', 'Cuba'),
    'FLAC_CV': emoji('&#x1F1E8&#x1F1FB', 'Cape Verde'),
    'FLAC_CW': emoji('&#x1F1E8&#x1F1FC', 'Curaçao'),
    'FLAC_CX': emoji('&#x1F1E8&#x1F1FD', 'Christmas Island'),
    'FLAC_CY': emoji('&#x1F1E8&#x1F1FE', 'Cyprus'),
    'FLAC_CZ': emoji('&#x1F1E8&#x1F1FF', 'Czechia'),
    'FLAC_DE': emoji('&#x1F1E9&#x1F1EA', 'Germany'),
    'FLAC_DG': emoji('&#x1F1E9&#x1F1EC', 'Diego Garcia'),
    'FLAC_DJ': emoji('&#x1F1E9&#x1F1EF', 'Djibouti'),
    'FLAC_DK': emoji('&#x1F1E9&#x1F1F0', 'Denmark'),
    'FLAC_DM': emoji('&#x1F1E9&#x1F1F2', 'Dominica'),
    'FLAC_DO': emoji('&#x1F1E9&#x1F1F4', 'Dominican Republic'),
    'FLAC_DZ': emoji('&#x1F1E9&#x1F1FF', 'Algeria'),
    'FLAC_EA': emoji('&#x1F1EA&#x1F1E6', 'Ceuta & Melilla'),
    'FLAC_EC': emoji('&#x1F1EA&#x1F1E8', 'Ecuador'),
    'FLAC_EE': emoji('&#x1F1EA&#x1F1EA', 'Estonia'),
    'FLAC_EG': emoji('&#x1F1EA&#x1F1EC', 'Egypt'),
    'FLAC_EH': emoji('&#x1F1EA&#x1F1ED', 'Western Sahara'),
    'FLAC_ER': emoji('&#x1F1EA&#x1F1F7', 'Eritrea'),
    'FLAC_ES': emoji('&#x1F1EA&#x1F1F8', 'Spain'),
    'FLAC_ET': emoji('&#x1F1EA&#x1F1F9', 'Ethiopia'),
    'FLAC_EU': emoji('&#x1F1EA&#x1F1FA', 'European Union'),
    'FLAC_FI': emoji('&#x1F1EB&#x1F1EE', 'Finland'),
    'FLAC_FJ': emoji('&#x1F1EB&#x1F1EF', 'Fiji'),
    'FLAC_FK': emoji('&#x1F1EB&#x1F1F0', 'Falkland Islands'),
    'FLAC_FM': emoji('&#x1F1EB&#x1F1F2', 'Micronesia'),
    'FLAC_FO': emoji('&#x1F1EB&#x1F1F4', 'Faroe Islands'),
    'FLAC_FR': emoji('&#x1F1EB&#x1F1F7', 'France'),
    'FLAC_GA': emoji('&#x1F1EC&#x1F1E6', 'Gabon'),
    'FLAC_GB': emoji('&#x1F1EC&#x1F1E7', 'United Kingdom'),
    'FLAC_GD': emoji('&#x1F1EC&#x1F1E9', 'Grenada'),
    'FLAC_GE': emoji('&#x1F1EC&#x1F1EA', 'Georgia'),
    'FLAC_GF': emoji('&#x1F1EC&#x1F1EB', 'French Guiana'),
    'FLAC_GG': emoji('&#x1F1EC&#x1F1EC', 'Guernsey'),
    'FLAC_GH': emoji('&#x1F1EC&#x1F1ED', 'Ghana'),
    'FLAC_GI': emoji('&#x1F1EC&#x1F1EE', 'Gibraltar'),
    'FLAC_GL': emoji('&#x1F1EC&#x1F1F1', 'Greenland'),
    'FLAC_GM': emoji('&#x1F1EC&#x1F1F2', 'Gambia'),
    'FLAC_GN': emoji('&#x1F1EC&#x1F1F3', 'Guinea'),
    'FLAC_GP': emoji('&#x1F1EC&#x1F1F5', 'Guadeloupe'),
    'FLAC_GQ': emoji('&#x1F1EC&#x1F1F6', 'Equatorial Guinea'),
    'FLAC_GR': emoji('&#x1F1EC&#x1F1F7', 'Greece'),
    'FLAC_GS': emoji('&#x1F1EC&#x1F1F8', 'South Georgia & South Sandwich Islands'),
    'FLAC_GT': emoji('&#x1F1EC&#x1F1F9', 'Guatemala'),
    'FLAC_GU': emoji('&#x1F1EC&#x1F1FA', 'Guam'),
    'FLAC_GW': emoji('&#x1F1EC&#x1F1FC', 'Guinea-Bissau'),
    'FLAC_GY': emoji('&#x1F1EC&#x1F1FE', 'Guyana'),
    'FLAC_HK': emoji('&#x1F1ED&#x1F1F0', 'Hong Kong SAR China'),
    'FLAC_HM': emoji('&#x1F1ED&#x1F1F2', 'Heard & McDonald Islands'),
    'FLAC_HN': emoji('&#x1F1ED&#x1F1F3', 'Honduras'),
    'FLAC_HR': emoji('&#x1F1ED&#x1F1F7', 'Croatia'),
    'FLAC_HT': emoji('&#x1F1ED&#x1F1F9', 'Haiti'),
    'FLAC_HU': emoji('&#x1F1ED&#x1F1FA', 'Hungary'),
    'FLAC_IC': emoji('&#x1F1EE&#x1F1E8', 'Canary Islands'),
    'FLAC_ID': emoji('&#x1F1EE&#x1F1E9', 'Indonesia'),
    'FLAC_IE': emoji('&#x1F1EE&#x1F1EA', 'Ireland'),
    'FLAC_IL': emoji('&#x1F1EE&#x1F1F1', 'Israel'),
    'FLAC_IM': emoji('&#x1F1EE&#x1F1F2', 'Isle of Man'),
    'FLAC_IN': emoji('&#x1F1EE&#x1F1F3', 'India'),
    'FLAC_IO': emoji('&#x1F1EE&#x1F1F4', 'British Indian Ocean Territory'),
    'FLAC_IQ': emoji('&#x1F1EE&#x1F1F6', 'Iraq'),
    'FLAC_IR': emoji('&#x1F1EE&#x1F1F7', 'Iran'),
    'FLAC_IS': emoji('&#x1F1EE&#x1F1F8', 'Iceland'),
    'FLAC_IT': emoji('&#x1F1EE&#x1F1F9', 'Italy'),
    'FLAC_JE': emoji('&#x1F1EF&#x1F1EA', 'Jersey'),
    'FLAC_JM': emoji('&#x1F1EF&#x1F1F2', 'Jamaica'),
    'FLAC_JO': emoji('&#x1F1EF&#x1F1F4', 'Jordan'),
    'FLAC_JP': emoji('&#x1F1EF&#x1F1F5', 'Japan'),
    'FLAC_KE': emoji('&#x1F1F0&#x1F1EA', 'Kenya'),
    'FLAC_KG': emoji('&#x1F1F0&#x1F1EC', 'Kyrgyzstan'),
    'FLAC_KH': emoji('&#x1F1F0&#x1F1ED', 'Cambodia'),
    'FLAC_KI': emoji('&#x1F1F0&#x1F1EE', 'Kiribati'),
    'FLAC_KM': emoji('&#x1F1F0&#x1F1F2', 'Comoros'),
    'FLAC_KN': emoji('&#x1F1F0&#x1F1F3', 'St. Kitts & Nevis'),
    'FLAC_KP': emoji('&#x1F1F0&#x1F1F5', 'North Korea'),
    'FLAC_KR': emoji('&#x1F1F0&#x1F1F7', 'South Korea'),
    'FLAC_KW': emoji('&#x1F1F0&#x1F1FC', 'Kuwait'),
    'FLAC_KY': emoji('&#x1F1F0&#x1F1FE', 'Cayman Islands'),
    'FLAC_KZ': emoji('&#x1F1F0&#x1F1FF', 'Kazakhstan'),
    'FLAC_LA': emoji('&#x1F1F1&#x1F1E6', 'Laos'),
    'FLAC_LB': emoji('&#x1F1F1&#x1F1E7', 'Lebanon'),
    'FLAC_LC': emoji('&#x1F1F1&#x1F1E8', 'St. Lucia'),
    'FLAC_LI': emoji('&#x1F1F1&#x1F1EE', 'Liechtenstein'),
    'FLAC_LK': emoji('&#x1F1F1&#x1F1F0', 'Sri Lanka'),
    'FLAC_LR': emoji('&#x1F1F1&#x1F1F7', 'Liberia'),
    'FLAC_LS': emoji('&#x1F1F1&#x1F1F8', 'Lesotho'),
    'FLAC_LT': emoji('&#x1F1F1&#x1F1F9', 'Lithuania'),
    'FLAC_LU': emoji('&#x1F1F1&#x1F1FA', 'Luxembourg'),
    'FLAC_LV': emoji('&#x1F1F1&#x1F1FB', 'Latvia'),
    'FLAC_LY': emoji('&#x1F1F1&#x1F1FE', 'Libya'),
    'FLAC_MA': emoji('&#x1F1F2&#x1F1E6', 'Morocco'),
    'FLAC_MC': emoji('&#x1F1F2&#x1F1E8', 'Monaco'),
    'FLAC_MD': emoji('&#x1F1F2&#x1F1E9', 'Moldova'),
    'FLAC_ME': emoji('&#x1F1F2&#x1F1EA', 'Montenegro'),
    'FLAC_MF': emoji('&#x1F1F2&#x1F1EB', 'St. Martin'),
    'FLAC_MG': emoji('&#x1F1F2&#x1F1EC', 'Madagascar'),
    'FLAC_MH': emoji('&#x1F1F2&#x1F1ED', 'Marshall Islands'),
    'FLAC_MK': emoji('&#x1F1F2&#x1F1F0', 'Macedonia'),
    'FLAC_ML': emoji('&#x1F1F2&#x1F1F1', 'Mali'),
    'FLAC_MM': emoji('&#x1F1F2&#x1F1F2', 'Myanmar (Burma)'),
    'FLAC_MN': emoji('&#x1F1F2&#x1F1F3', 'Mongolia'),
    'FLAC_MO': emoji('&#x1F1F2&#x1F1F4', 'Macao SAR China'),
    'FLAC_MP': emoji('&#x1F1F2&#x1F1F5', 'Northern Mariana Islands'),
    'FLAC_MQ': emoji('&#x1F1F2&#x1F1F6', 'Martinique'),
    'FLAC_MR': emoji('&#x1F1F2&#x1F1F7', 'Mauritania'),
    'FLAC_MS': emoji('&#x1F1F2&#x1F1F8', 'Montserrat'),
    'FLAC_MT': emoji('&#x1F1F2&#x1F1F9', 'Malta'),
    'FLAC_MU': emoji('&#x1F1F2&#x1F1FA', 'Mauritius'),
    'FLAC_MV': emoji('&#x1F1F2&#x1F1FB', 'Maldives'),
    'FLAC_MW': emoji('&#x1F1F2&#x1F1FC', 'Malawi'),
    'FLAC_MX': emoji('&#x1F1F2&#x1F1FD', 'Mexico'),
    'FLAC_MY': emoji('&#x1F1F2&#x1F1FE', 'Malaysia'),
    'FLAC_MZ': emoji('&#x1F1F2&#x1F1FF', 'Mozambique'),
    'FLAC_NA': emoji('&#x1F1F3&#x1F1E6', 'Namibia'),
    'FLAC_NC': emoji('&#x1F1F3&#x1F1E8', 'New Caledonia'),
    'FLAC_NE': emoji('&#x1F1F3&#x1F1EA', 'Niger'),
    'FLAC_NF': emoji('&#x1F1F3&#x1F1EB', 'Norfolk Island'),
    'FLAC_NG': emoji('&#x1F1F3&#x1F1EC', 'Nigeria'),
    'FLAC_NI': emoji('&#x1F1F3&#x1F1EE', 'Nicaragua'),
    'FLAC_NL': emoji('&#x1F1F3&#x1F1F1', 'Netherlands'),
    'FLAC_NO': emoji('&#x1F1F3&#x1F1F4', 'Norway'),
    'FLAC_NP': emoji('&#x1F1F3&#x1F1F5', 'Nepal'),
    'FLAC_NR': emoji('&#x1F1F3&#x1F1F7', 'Nauru'),
    'FLAC_NU': emoji('&#x1F1F3&#x1F1FA', 'Niue'),
    'FLAC_NZ': emoji('&#x1F1F3&#x1F1FF', 'New Zealand'),
    'FLAC_OM': emoji('&#x1F1F4&#x1F1F2', 'Oman '),
    'FLAC_PA': emoji('&#x1F1F5&#x1F1E6', 'Panama'),
    'FLAC_PE': emoji('&#x1F1F5&#x1F1EA', 'Peru'),
    'FLAC_PF': emoji('&#x1F1F5&#x1F1EB', 'French Polynesia'),
    'FLAC_PG': emoji('&#x1F1F5&#x1F1EC', 'Papua New Guinea'),
    'FLAC_PH': emoji('&#x1F1F5&#x1F1ED', 'Philippines'),
    'FLAC_PK': emoji('&#x1F1F5&#x1F1F0', 'Pakistan'),
    'FLAC_PL': emoji('&#x1F1F5&#x1F1F1', 'Poland'),
    'FLAC_PM': emoji('&#x1F1F5&#x1F1F2', 'St. Pierre & Miquelon'),
    'FLAC_PN': emoji('&#x1F1F5&#x1F1F3', 'Pitcairn Islands'),
    'FLAC_PR': emoji('&#x1F1F5&#x1F1F7', 'Puerto Rico'),
    'FLAC_PS': emoji('&#x1F1F5&#x1F1F8', 'Palestinian Territories'),
    'FLAC_PT': emoji('&#x1F1F5&#x1F1F9', 'Portugal'),
    'FLAC_PW': emoji('&#x1F1F5&#x1F1FC', 'Palau'),
    'FLAC_PY': emoji('&#x1F1F5&#x1F1FE', 'Paraguay'),
    'FLAC_QA': emoji('&#x1F1F6&#x1F1E6', 'Qatar'),
    'FLAC_RE': emoji('&#x1F1F7&#x1F1EA', 'Réunion'),
    'FLAC_RO': emoji('&#x1F1F7&#x1F1F4', 'Romania'),
    'FLAC_RS': emoji('&#x1F1F7&#x1F1F8', 'Serbia'),
    'FLAC_RU': emoji('&#x1F1F7&#x1F1FA', 'Russia'),
    'FLAC_RW': emoji('&#x1F1F7&#x1F1FC', 'Rwanda'),
    'FLAC_SA': emoji('&#x1F1F8&#x1F1E6', 'Saudi Arabia'),
    'FLAC_SB': emoji('&#x1F1F8&#x1F1E7', 'Solomon Islands'),
    'FLAC_SC': emoji('&#x1F1F8&#x1F1E8', 'Seychelles'),
    'FLAC_SD': emoji('&#x1F1F8&#x1F1E9', 'Sudan'),
    'FLAC_SE': emoji('&#x1F1F8&#x1F1EA', 'Sweden'),
    'FLAC_SG': emoji('&#x1F1F8&#x1F1EC', 'Singapore'),
    'FLAC_SH': emoji('&#x1F1F8&#x1F1ED', 'St. Helena'),
    'FLAC_SI': emoji('&#x1F1F8&#x1F1EE', 'Slovenia'),
    'FLAC_SJ': emoji('&#x1F1F8&#x1F1EF', 'Svalbard & Jan Mayen'),
    'FLAC_SK': emoji('&#x1F1F8&#x1F1F0', 'Slovakia'),
    'FLAC_SL': emoji('&#x1F1F8&#x1F1F1', 'Sierra Leone'),
    'FLAC_SM': emoji('&#x1F1F8&#x1F1F2', 'San Marino'),
    'FLAC_SN': emoji('&#x1F1F8&#x1F1F3', 'Senegal'),
    'FLAC_SO': emoji('&#x1F1F8&#x1F1F4', 'Somalia'),
    'FLAC_SR': emoji('&#x1F1F8&#x1F1F7', 'Suriname'),
    'FLAC_SS': emoji('&#x1F1F8&#x1F1F8', 'South Sudan'),
    'FLAC_ST': emoji('&#x1F1F8&#x1F1F9', 'São Tomé & Príncipe'),
    'FLAC_SV': emoji('&#x1F1F8&#x1F1FB', 'El Salvador'),
    'FLAC_SC': emoji('&#x1F1F8&#x1F1FD', 'Sint Maarten'),
    'FLAC_SY': emoji('&#x1F1F8&#x1F1FE', 'Syria'),
    'FLAC_SZ': emoji('&#x1F1F8&#x1F1FF', 'Eswatini'),
    'FLAC_TA': emoji('&#x1F1F9&#x1F1E6', 'Tristan da Cunha'),
    'FLAC_TC': emoji('&#x1F1F9&#x1F1E8', 'Turks & Caicos Islands'),
    'FLAC_TD': emoji('&#x1F1F9&#x1F1E9', 'Chad'),
    'FLAC_TF': emoji('&#x1F1F9&#x1F1EB', 'French Southern Territories'),
    'FLAC_TG': emoji('&#x1F1F9&#x1F1EC', 'Togo'),
    'FLAC_TH': emoji('&#x1F1F9&#x1F1ED', 'Thailand'),
    'FLAC_TJ': emoji('&#x1F1F9&#x1F1EF', 'Tajikistan'),
    'FLAC_TK': emoji('&#x1F1F9&#x1F1F0', 'Tokelau'),
    'FLAC_TL': emoji('&#x1F1F9&#x1F1F1', 'Timor-Leste'),
    'FLAC_TM': emoji('&#x1F1F9&#x1F1F2', 'Turkmenistan'),
    'FLAC_TN': emoji('&#x1F1F9&#x1F1F3', 'Tunisia'),
    'FLAC_TO': emoji('&#x1F1F9&#x1F1F4', 'Tonga'),
    'FLAC_TR': emoji('&#x1F1F9&#x1F1F7', 'Turkey'),
    'FLAC_TT': emoji('&#x1F1F9&#x1F1F9', 'Trinidad & Tobago'),
    'FLAC_TV': emoji('&#x1F1F9&#x1F1FB', 'Tuvalu'),
    'FLAC_TW': emoji('&#x1F1F9&#x1F1FC', 'Taiwan'),
    'FLAC_TZ': emoji('&#x1F1F9&#x1F1FF', 'Tanzania'),
    'FLAC_UA': emoji('&#x1F1FA&#x1F1E6', 'Ukraine'),
    'FLAC_UG': emoji('&#x1F1FA&#x1F1EC', 'Uganda'),
    'FLAC_UM': emoji('&#x1F1FA&#x1F1F2', 'U.S. Outlying Islands'),
    'FLAC_UN': emoji('&#x1F1FA&#x1F1F3', 'United Nations'),
    'FLAC_US': emoji('&#x1F1FA&#x1F1F8', 'United States'),
    'FLAC_UY': emoji('&#x1F1FA&#x1F1FE', 'Uruguay'),
    'FLAC_UZ': emoji('&#x1F1FA&#x1F1FF', 'Uzbekistan'),
    'FLAC_VA': emoji('&#x1F1FB&#x1F1E6', 'Vatican City'),
    'FLAC_VC': emoji('&#x1F1FB&#x1F1E8', 'St. Vincent & Grenadines'),
    'FLAC_VE': emoji('&#x1F1FB&#x1F1EA', 'Venezuela'),
    'FLAC_VG': emoji('&#x1F1FB&#x1F1EC', 'British Virgin Islands'),
    'FLAC_VI': emoji('&#x1F1FB&#x1F1EE', 'U.S. Virgin Islands'),
    'FLAC_VN': emoji('&#x1F1FB&#x1F1F3', 'Vietnam'),
    'FLAC_VU': emoji('&#x1F1FB&#x1F1FA', 'Vanuatu'),
    'FLAC_WF': emoji('&#x1F1FC&#x1F1EB', 'Wallis & Futuna'),
    'FLAC_WS': emoji('&#x1F1FC&#x1F1F8', 'Samoa'),
    'FLAC_XK': emoji('&#x1F1FD&#x1F1F0', 'Kosovo'),
    'FLAC_YE': emoji('&#x1F1FE&#x1F1EA', 'Yemen'),
    'FLAC_YT': emoji('&#x1F1FE&#x1F1F9', 'Mayotte'),
    'FLAC_ZA': emoji('&#x1F1FF&#x1F1E6', 'South Africa'),
    'FLAC_ZM': emoji('&#x1F1FF&#x1F1F2', 'Zambia'),
    'FLAG_ZW': emoji('&#x1F1FF&#x1F1FC', 'Zimbabwe'),
}


def get_emoji(name):
    """Returns a Unicode for an emoji given the name or blank if not saved.

    Args:
        name: string with the emoji name.

    Returns:
        Unicode string for the emoji if it exists or a blank string otherwise.
    """
    name_upper = name.upper()
    emoji_object = EMOJI_MAP.get(name_upper)
    if emoji_object:
        return emoji_object.code
    return ''


def get_helper_from_unicode(code):
    """Returns a helper string from an emoji Unicode code point.

    Args:
        code: a Unicode code point for an emoji.

    Returns:
        Helper text as a string or an empty string if emoji is not configured.
    """
    code_upper = code.upper()
    for emoji_object in iter(EMOJI_MAP.values()):
        if code_upper == emoji_object.code.upper():
            return emoji_object.help
    return ''


def get_emojis_as_dict():
    """Returns a dictionary with emoji codes and helper texts.

    Returns:
        Dict with emoji unicode code points as key and helper text as value.
    """
    return {e.code: e.help for e in iter(EMOJI_MAP.values())}
