<!--
Copyright 2025 Google Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<template>
  <section>
    <!-- NEW: Empty state when no questions exist -->
    <div v-if="!isLoading && questionsTotal === 0 && isLogAnalyzerAvailable" class="px-6 py-16 text-center">
      <v-icon size="80" color="disabled" class="mb-4">mdi-text-box-search-outline</v-icon>
      <h2 class="text-h4 font-weight-bold mb-4">Start Your AI-Powered Investigation</h2>
      <p class="mb-8 mx-auto" style="max-width: 600px">
        There are currently no investigative questions in this report. Click the button below to have the
        connected Log Reasoning Agent analyze all timeline data in this sketch.
        It will automatically generate key findings and investigative questions to kickstart your analysis.
      </p>
      <v-btn
        size="large"
        color="primary"
        @click="runLogAnalysis()"
        :loading="isGeneratingReport"
        :disabled="isGeneratingReport"
      >
        <v-icon left class="mr-2">mdi-creation</v-icon>
        {{ isGeneratingReport ? 'Generating Report...' : 'Generate Initial Report' }}
      </v-btn>
    </div>
    <!-- Empty state for the manual investigation mode without AI features enabled. -->
    <div v-else-if="!isLoading && questionsTotal === 0 && !isLogAnalyzerAvailable" class="px-6 py-16 text-center">
      <v-icon size="80" color="disabled" class="mb-4">mdi-text-box-search-outline</v-icon>
      <h2 class="text-h4 font-weight-bold mb-4">Start Your Investigation</h2>
      <p class="mb-8 mx-auto" style="max-width: 600px;">
        There are currently no investigative questions in this report.
        Click the button below to select or add a question to get started.
      </p>
      <v-btn
        size="large"
        color="primary"
        @click="toggleModal"
      >
        <v-icon left class="mr-2">mdi-plus</v-icon>
        Add Question
      </v-btn>
      <v-dialog
        transition="dialog-bottom-transition"
        v-model="showModal"
        width="auto"
      >
        <AddQuestionModal @close-modal="toggleModal" />
      </v-dialog>
    </div>
    <!-- Existing view for when questions are present -->
    <div v-else>
      <header class="report-header px-6 pt-8 pb-8 mb-8">
        <h2 class="mb-4 text-h3 font-weight-bold">Investigation Report</h2>
        <div class="d-flex align-center justify-space-between">
          <div class="question-status-chip__group" v-if="hasAiCollaboration">
            <v-chip title="Generated by AI" class="question-status-chip question-status-chip--ai" size="small">
              <CreationIcon :width="20" :height="20" class="mr-2" /> AI Collaboration
            </v-chip>
          </div>
          <v-spacer />
          <div class="d-flex align-center ga-4">
            <v-btn v-if="reportLocked" variant="text" size="small" color="primary" @click="unlockReport()">
              <v-icon icon="mdi-file-edit-outline" class="mr-1" left small />
              Edit</v-btn
            >
            <v-btn variant="text" size="small" color="primary" @click="downloadReport()" v-if="reportLocked">
              <v-icon icon="mdi-download-circle-outline" class="mr-1" left small />
              Download</v-btn
            >
            <v-tooltip location="bottom" :disabled="canCompleteInvestigation">
              <template v-slot:activator="{ props }">
                <div v-bind="props">
                  <v-btn
                    v-if="!reportLocked"
                    class="rounded-lg text-caption text-uppercase"
                    height=""
                    :variant="unsavedQuestions?.length > 0 ? 'outlined' : 'flat'"
                    color="primary"
                    :disabled="!canCompleteInvestigation"
                    @click="toggleShowConfirmationModal()"
                  >
                    Close investigation
                  </v-btn>
                </div>
              </template>
              <span>At least one question must be answered (verified) to close the investigation.</span>
            </v-tooltip>
          </div>
        </div>
      </header>
      <form class="px-6 mb-12">
        <div class="report-form-group mb-6 w-75">
          <label for="name" class="font-weight-bold">Name</label>
          <v-text-field
            hide-details="auto"
            id="name"
            name="name"
            v-model="name"
            variant="outlined"
            density="compact"
            :disabled="reportLocked"
          ></v-text-field>
          <label for="analysts" class="font-weight-bold">Analyst(s)</label>
          <v-text-field
            hide-details="auto"
            id="analysts"
            name="analysts"
            variant="outlined"
            density="compact"
            v-model="analysts"
            :disabled="reportLocked"
          ></v-text-field>
        </div>
        <div class="report-form-group ga-6 mb-6 w-75">
          <p class="font-weight-bold">Finalized Date & Time</p>
          <p class="font-italic report-auto-timestamp">{{ finalizedTime }}</p>
        </div>
        <div class="report-form-group ga-6 mb-12 w-75" v-if="questionsTotal">
          <p class="font-weight-bold">Progress</p>
          <p>{{ completedQuestionsTotal }} / {{ questionsTotal }} questions answered</p>
        </div>
        <SummarySection :reportLocked="reportLocked" />
      </form>
      <div class="px-6" v-if="questionsTotal">
        <div class="d-flex justify-space-between align-center mb-5">
          <h3 class="text-h6 font-weight-bold">Key Findings</h3>
          <v-btn
            v-if="isSynthesizeAvailable"
            variant="text"
            size="small"
            color="primary"
            @click="synthesizeAllMissingAnswers"
            :loading="isSynthesizingAll"
            :disabled="!canSynthesizeAll"
          >
            <v-icon left class="mr-2">mdi-creation</v-icon>
            Generate draft answers
          </v-btn>
        </div>
        <FilterBar
          ref="filterBar"
          :questions-total="questionsTotal"
          :questions="questions"
          :expanded="true"
          :completed-questions-total="completedQuestionsTotal"
          @filters-changed="handleFiltersChanged"
          view="report"
        />
        <v-divider></v-divider>
        <ol class="questions-list mt-6">
          <KeyFindingItem
            v-for="(question, index) in filteredQuestions"
            :question="question"
            :index="index"
            :key="question.id"
            :reportLocked="reportLocked"
          />
        </ol>
      </div>
    </div>
  </section>
  <v-dialog transition="dialog-bottom-transition" v-model="showConfirmationModal" width="auto">
    <CompleteInvestigationModal
      @close-modal="showConfirmationModal = false"
      @completed="handleInvestigationCompleted"
      :questions="questions"
      :unsavedQuestions="unsavedQuestions"
    />
  </v-dialog>
</template>
<script>
import { ReportStatus, useAppStore } from '@/stores/app'
import RestApiClient from '@/utils/RestApiClient'
import dayjs from 'dayjs'
import { debounce } from 'lodash'
import generatePdf from '../_utils/pdf-generator'
import FilterBar from '../Sidebar/FilterBar.vue'
import SummarySection from './SummarySection.vue'

export default {
  inject: ['runLogAnalysis', 'isGeneratingReport', 'regenerateQuestions'],
  components: {
    SummarySection,
    FilterBar,
  },
  props: {
    questions: Array,
    questionsTotal: Number,
    completedQuestionsTotal: Number,
    reportLocked: Boolean,
    isLoading: Boolean,
  },
  data() {
    const store = useAppStore()
    return {
      store,
      showConfirmationModal: false,
      isSynthesizingAll: false,
      filteredQuestions: [],
      showModal: false,
      isCompleting: false,
    }
  },
  computed: {
    analysts: {
      get: function () {
        return this.store.report?.content?.analysts
      },
      set: function (value) {
        this.store.report.content.analysts = value
        this.updateContent('analysts', value)
      },
    },
    hasAiCollaboration() {
      if (!this.questions || !this.questions.length) {
        return false
      }
      return this.questions.some(
        (q) => q.automated || (q.conclusions && q.conclusions.some((c) => c.automated))
      )
    },
    systemSettings() {
      return this.store.systemSettings;
    },
    name: {
      get: function () {
        if (!this.store.report?.content?.name) {
          return this.store.sketch.name
        }
        return this.store.report?.content?.name
      },
      set: function (value) {
        this.store.report.content.name = value
        this.updateContent('name', value)
      },
    },
    summary() {
      return this.store.report.content.summary
    },
    finalizedTime() {
      return this.store.report?.content?.completedDateTime
        ? dayjs(this.store.report.content.completedDateTime).utc()
        : 'It will be automatically recorded upon closure.'
    },
    sortedQuestions() {
      if (!this.questions || this.questions.length === 0) {
        return []
      }
      return [...this.questions].sort((a, b) => a.id - b.id)
    },
    isLogAnalyzerAvailable() {
      return this.systemSettings.LLM_FEATURES_AVAILABLE?.log_analyzer
    },
    isSynthesizeAvailable() {
      if (
        this.store.systemSettings.LLM_FEATURES_AVAILABLE?.llm_synthesize === true ||
        this.store.systemSettings.LLM_FEATURES_AVAILABLE?.default === true
      ) {
        return true
      }
      return false
    },
    questionsWithoutAnswers() {
      const answeredQuestionIds = new Set(
        (this.store.report?.content?.conclusionSummaries || []).map((s) => s.questionId)
      )
      return this.sortedQuestions.filter((q) => !answeredQuestionIds.has(q.id))
    },
    canSynthesizeAll() {
      return (
        this.isSynthesizeAvailable &&
        this.questionsWithoutAnswers.length > 0 &&
        !this.isSynthesizingAll &&
        !this.isGeneratingReport
      )
    },
    canCompleteInvestigation() {
      return this.questions.some((q) => q.status?.status === 'verified')
    },
    unsavedQuestions() {
      return this.questions.filter(
        (question) => question.status?.status !== 'verified' && question.status?.status !== 'rejected'
      )
    },
  },
  methods: {
    toggleModal() {
      this.showModal = !this.showModal
    },
    handleInvestigationCompleted() {
      this.showConfirmationModal = false
      this.regenerateQuestions()
    },
    async completeInvestigation() {
      this.isCompleting = true
      try {
        await this.store.updateReport({
          status: ReportStatus.VERIFIED,
          completedDateTime: dayjs(),
        })
        this.store.setNotification({
          text: 'Report Created',
          icon: 'mdi-file-check-outline',
          type: 'success',
        })
      } catch (error) {
        console.error(error)
        this.store.setNotification({
          text: 'Unable to create this report. Please try again.',
          icon: 'mdi-alert-circle-outline',
          type: 'error',
        })
      } finally {
        this.isCompleting = false
      }
    },
    toggleShowConfirmationModal() {
      if (this.unsavedQuestions.length === 0) {
        this.completeInvestigation()
      } else {
        this.showConfirmationModal = !this.showConfirmationModal
      }
    },
    async synthesizeAllMissingAnswers() {
      const questionsToProcess = this.questionsWithoutAnswers
      if (questionsToProcess.length === 0) {
        console.error('All questions already have an answer.')
        return
      }
      this.isSynthesizingAll = true
      const sketchId = this.store.sketch.id
      let successfulCount = 0
      let failedCount = 0

      for (const question of questionsToProcess) {
        try {
          const response = await RestApiClient.llmRequest(sketchId, 'llm_synthesize', { question_id: question.id })
          const answer = response.data.response

          const newSummary = {
            questionId: question.id,
            timestamp: dayjs(),
            value: answer,
            user: '<AI>',
          }

          const existingSummaries = this.store.report?.content?.conclusionSummaries || []

          await this.store.updateReport({
            conclusionSummaries: [newSummary, ...existingSummaries],
          })
          successfulCount++
        } catch (error) {
          failedCount++
          console.error(`Failed to synthesize answer for question ${question.id}:`, error)
        }
      }

      if (failedCount > 0) {
        console.error(`Synthesized ${successfulCount} answers, but ${failedCount} failed.`)
      } else {
        console.log(`Successfully synthesized answers for ${successfulCount} questions.`)
      }

      this.isSynthesizingAll = false
    },
    downloadReport() {
      const verifiedQuestions = this.questions.filter((q) => q.status?.status === 'verified')
      const pdfGenerator = new generatePdf({
        analysts: this.analysts,
        name: this.name,
        summary: this.summary,
        finalizedTime: this.finalizedTime,
        questions: verifiedQuestions,
        conclusionSummaries: this.store.report?.content?.conclusionSummaries || [],
        id: this.store.report.id,
        questionsTotal: this.questionsTotal,
        completedQuestionsTotal: this.completedQuestionsTotal,
      })
      pdfGenerator.generatePdf()
    },
    async unlockReport() {
      try {
        await this.store.updateReport({
          status: ReportStatus.UNVERIFIED,
          completedDateTime: null,
        })
        this.store.setNotification({
          text: 'Report Unlocked',
          icon: 'mdi-lock-open-variant-outline',
          type: 'info',
        })
      } catch (error) {
        console.error(error)
        this.store.setNotification({
          text: 'Unable to unlock this report. Please try again.',
          icon: 'mdi-alert-circle-outline',
          type: 'error',
        })
      }
    },
    updateContent: debounce(function (key, value) {
      this.store.updateReport({ [key]: value })
    }, 200),
    handleFiltersChanged(filteredQuestions) {
      // Exclude rejected questions from the main report view's list
      this.filteredQuestions = filteredQuestions.filter(q => q.status?.status !== 'rejected');
    },
  },
};
</script>
<style>
.questions-list {
  list-style: none;
}
.question::marker {
  font-size: inherit;
  font-weight: inherit;
}
.report-form-group {
  display: grid;
  grid-template-columns: 160px 1fr;
  row-gap: 10px;
  column-gap: 20px;
  align-items: center;
}
.report-header {
  background-color: var(--theme-ai-color-gray-50);
  border-bottom: 1px solid var(--theme-ai-color-gray-100);
  min-height: 212px;

  h2 {
    max-width: 800px;
  }
}
.report-auto-timestamp {
  color: #5f6368;
}
</style>
