<!--
Copyright 2025 Google Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<template>
  <li class="question mb-6">
    <div class="question__chip-group">
      <QuestionPrioritySelect :question="question" />

      <v-chip
        :title="questionStatus"
        :prepend-icon="statusIcon"
        :class="['question-status-chip', `question-status-chip--${questionStatus}`]"
        size="small"
      >
        {{ questionStatus.replace(/-/g, ' ') }}
      </v-chip>

      <div class="question-status-chip__group" v-if="!question.user?.name">
        <v-chip title="Generated by AI" :class="['question-status-chip', `question-status-chip--ai`]" size="small">
          <CreationIcon :width="20" :height="20" class="mr-2" /> Generated by AI
        </v-chip>
      </div>
      <div class="question-status-chip__group" v-if="question.user?.name">
        <v-chip title="User Generated" :class="['question-status-chip', `question-status-chip--ai`]" size="small">
          <v-icon icon="mdi-account-outline" class="mr-2" /> User Generated
        </v-chip>
      </div>
    </div>
    <p class="text-h6 font-weight-medium">{{ question.name }}</p>

    <!-- If a custom summary exists, show it -->
    <div v-if="latestConclusionSummary" class="my-4 ml-4">
      <div class="conclusion-summary" v-html="renderedSummary"></div>
    </div>
    <!-- Otherwise, fall back to a call to action to review the question -->
    <div v-else class="my-4 ml-4 font-italic text-body-2">
      <p v-if="question.conclusions && question.conclusions.length > 0">
        TODO: No answer has been provided for this question yet.
        <a href="#" @click.prevent="setActiveQuestion"> Review the conclusions and add your answer. </a>
      </p>
      <p v-else>
        TODO: No answer has been provided for this question yet.
        <a href="#" @click.prevent="setActiveQuestion"> Add your conclusion and answer to this question. </a>
      </p>
    </div>
    <QuestionActionsStrip
      :question="question"
      :reportLocked="reportLocked"
      :isApproved="isApproved"
      variant="compact"
      :index="index"
    />
    <v-divider></v-divider>
  </li>
</template>

<script>
import { useAppStore } from '@/stores/app'
import DOMPurify from 'dompurify'
import { marked } from 'marked'
import QuestionPrioritySelect from './QuestionPrioritySelect.vue'
import CreationIcon from '@/components/Icons/CreationIcon.vue'

export default {
  components: {
    QuestionPrioritySelect,
    CreationIcon,
  },
  props: { question: Object, index: Number, reportLocked: Boolean },
  inject: ['updateQuestion', 'confirmRemoveQuestion'],
  data() {
    return {
      store: useAppStore(),
    }
  },
  computed: {
    isApproved() {
      return this.question?.status?.status === 'verified'
    },
    order() {
      return this.index + 1
    },
    questionStatus() {
      return this.question?.status?.status || 'new'
    },
    statusIcon() {
      switch (this.questionStatus) {
        case 'verified':
          return 'mdi-check-circle-outline'
        case 'rejected':
          return 'mdi-close'
        case 'pending-review':
          return 'mdi-magnify'
        case 'new':
          return 'mdi-star-outline'
        default:
          return 'mdi-help-circle-outline'
      }
    },
    latestConclusionSummary() {
      const summaries = this.store.report?.content?.conclusionSummaries?.filter(
        (summary) => summary.questionId === this.question.id
      )
      // New summaries are prepended, so the latest is at index 0.
      return summaries?.[0]?.value || null
    },
    renderedSummary() {
      if (this.latestConclusionSummary) {
        const unsafeHtml = marked(this.latestConclusionSummary)
        return DOMPurify.sanitize(unsafeHtml)
      }
      return ''
    },
  },
  methods: {
    setActiveQuestion() {
      this.store.setActiveQuestion(this.question)
    },
  },
}
</script>

<style scoped>
.questions-list {
  list-style: none;
}

.question::marker {
  font-size: inherit;
  font-weight: inherit;
}

.question__chip-group {
  display: flex;
  gap: 10px;
  align-items: center;
  justify-content: flex-start;
  padding: 0 0 9px;

  > * {
    flex: 0 0 auto;
  }
}

.report-form-group {
  display: grid;
  grid-template-columns: 160px 1fr;
  row-gap: 10px;
  column-gap: 20px;
  align-items: center;
}

.report-header {
  background-color: #fafafa;
  border: 1px solid #dcdcdc;
}

.report-auto-timestamp {
  color: #5f6368;
}

.conclusion-summary {
  padding: 8px 12px;
  border: 1px solid #ccc;
  background-color: #f5f5f5;
  border-radius: 4px;
  line-height: 1.5;
  overflow-y: auto;
}

.theme--dark .conclusion-summary {
  background-color: #333;
  border-color: #555;
}

/* Deep selectors to style the content rendered by v-html */
.conclusion-summary :deep(p) {
  margin-bottom: 1em;
}
.conclusion-summary :deep(ul),
.conclusion-summary :deep(ol) {
  padding-left: 2em;
  margin-bottom: 1em;
  list-style-position: inside;
}
.conclusion-summary :deep(li) {
  margin-bottom: 0.5em;
}
.conclusion-summary :deep(code) {
  background-color: #e0e0e0;
  padding: 0.2em 0.4em;
  border-radius: 3px;
  font-family: monospace;
}

.theme--dark .conclusion-summary :deep(code) {
  background-color: #424242;
}
</style>
