"""Refactor Scenario models

Revision ID: 011cabf3aef0
Revises: 710c224732e1
Create Date: 2024-02-20 08:26:06.886347

"""

# This code is auto generated. Ignore linter errors.


# revision identifiers, used by Alembic.
revision = "011cabf3aef0"
down_revision = "710c224732e1"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("facet", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sketch_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "sketch", ["sketch_id"], ["id"])

    with op.batch_alter_table("investigativequestion", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sketch_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("scenario_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "scenario", ["scenario_id"], ["id"])
        batch_op.create_foreign_key(None, "sketch", ["sketch_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("investigativequestion", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("scenario_id")
        batch_op.drop_column("sketch_id")

    with op.batch_alter_table("facet", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("sketch_id")

    # ### end Alembic commands ###
