"""question refactor add approach and add dfiq id

Revision ID: 5c3ba044dc64
Revises: a3b082c9e6e9
Create Date: 2023-04-13 09:51:05.692869

"""
# This code is auto generated. Ignore linter errors.
# pylint: skip-file


# revision identifiers, used by Alembic.
revision = "5c3ba044dc64"
down_revision = "a3b082c9e6e9"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("investigativequestion_searchtemplate")
    op.drop_table("investigativequestion_sigmarule")
    op.add_column(
        "facet", sa.Column("dfiq_identifier", sa.UnicodeText(), nullable=True)
    )
    op.add_column(
        "investigativequestion",
        sa.Column("dfiq_identifier", sa.UnicodeText(), nullable=True),
    )
    op.add_column(
        "scenario", sa.Column("dfiq_identifier", sa.UnicodeText(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scenario", "dfiq_identifier")
    op.drop_column("investigativequestion", "dfiq_identifier")
    op.drop_column("facet", "dfiq_identifier")
    op.create_table(
        "investigativequestion_sigmarule",
        sa.Column(
            "investigativequestion_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("sigmarule_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["investigativequestion_id"],
            ["investigativequestion.id"],
            name="investigativequestion_sigmarule_investigativequestion_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["sigmarule_id"],
            ["sigmarule.id"],
            name="investigativequestion_sigmarule_sigmarule_id_fkey",
        ),
    )
    op.create_table(
        "investigativequestion_searchtemplate",
        sa.Column(
            "investigativequestion_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "searchtemplate_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["investigativequestion_id"],
            ["investigativequestion.id"],
            name="investigativequestion_searchtempl_investigativequestion_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["searchtemplate_id"],
            ["searchtemplate.id"],
            name="investigativequestion_searchtemplate_searchtemplate_id_fkey",
        ),
    )
    # ### end Alembic commands ###
