"""Add description to View

Revision ID: 6e69f2cfcac1
Revises: 7d48bf36b244
Create Date: 2020-03-18 19:04:08.121530

"""

# This code is auto generated. Ignore linter errors.


# revision identifiers, used by Alembic.
revision = "6e69f2cfcac1"
down_revision = "7d48bf36b244"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("view", sa.Column("description", sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("view", "description")
    # ### end Alembic commands ###
