"""Extend SearchTemplate

Revision ID: a3b082c9e6e9
Revises: 180a387da650
Create Date: 2022-09-27 14:01:27.620470

"""

# This code is auto generated. Ignore linter errors.


# revision identifiers, used by Alembic.
revision = "a3b082c9e6e9"
down_revision = "180a387da650"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "searchtemplate", sa.Column("short_name", sa.Unicode(length=255), nullable=True)
    )
    op.add_column(
        "searchtemplate", sa.Column("template_json", sa.UnicodeText(), nullable=True)
    )
    op.add_column(
        "searchtemplate",
        sa.Column("template_uuid", sa.Unicode(length=255), nullable=True),
    )
    op.create_unique_constraint(None, "searchtemplate", ["template_uuid"])
    op.add_column(
        "view", sa.Column("searchtemplate_json", sa.UnicodeText(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("view", "searchtemplate_json")
    op.drop_constraint(None, "searchtemplate", type_="unique")
    op.drop_column("searchtemplate", "template_uuid")
    op.drop_column("searchtemplate", "template_json")
    op.drop_column("searchtemplate", "short_name")
    # ### end Alembic commands ###
