"""empty message

Revision ID: b11dea30835c
Revises: 64c00337b9d1
Create Date: 2020-04-02 14:40:42.286566

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b11dea30835c'
down_revision = '64c00337b9d1'



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'aggregation',
        sa.Column('aggregationgroup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, 'aggregation', 'aggregationgroup',
        ['aggregationgroup_id'], ['id'])
    op.drop_column('aggregationgroup', 'agg_type')
    op.drop_column('aggregationgroup', 'parameters')
    op.drop_column('aggregationgroup', 'chart_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'aggregationgroup', sa.Column(
            'chart_type', sa.VARCHAR(length=255),
            autoincrement=False, nullable=True))
    op.add_column(
        'aggregationgroup', sa.Column(
            'parameters', sa.TEXT(), autoincrement=False, nullable=True))
    op.a0dd_column(
        'aggregationgroup', sa.Column(
            'agg_type', sa.VARCHAR(length=255), autoincrement=False,
            nullable=True))
    op.drop_constraint(None, 'aggregation', type_='foreignkey')
    op.drop_column('aggregation', 'aggregationgroup_id')
    # ### end Alembic commands ###
