"""empty message

Revision ID: c3d0f1db66d0
Revises: 36e85b266dba
Create Date: 2016-09-09 12:41:22.410715

"""
# This code is auto generated. Ignore linter errors.
# pylint: skip-file

# revision identifiers, used by Alembic.
revision = 'c3d0f1db66d0'
down_revision = '36e85b266dba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cannedview', sa.Column('name', sa.Unicode(length=255), nullable=True))
    op.add_column('cannedview', sa.Column('query_dsl', sa.UnicodeText(), nullable=True))
    op.add_column('cannedview', sa.Column('query_filter', sa.UnicodeText(), nullable=True))
    op.add_column('cannedview', sa.Column('query_string', sa.Unicode(length=255), nullable=True))
    op.add_column('cannedview', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cannedview', 'user', ['user_id'], ['id'])
    op.add_column('view', sa.Column('cannedview_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'view', 'cannedview', ['cannedview_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'view', type_='foreignkey')
    op.drop_column('view', 'cannedview_id')
    op.drop_constraint(None, 'cannedview', type_='foreignkey')
    op.drop_column('cannedview', 'user_id')
    op.drop_column('cannedview', 'query_string')
    op.drop_column('cannedview', 'query_filter')
    op.drop_column('cannedview', 'query_dsl')
    op.drop_column('cannedview', 'name')
    ### end Alembic commands ###
