"""Add UUID field to DFIQ models

Revision ID: c5560d97a2c8
Revises: 011cabf3aef0
Create Date: 2024-08-22 09:24:34.745006

"""

# This code is auto generated. Ignore linter errors.


# revision identifiers, used by Alembic.
revision = "c5560d97a2c8"
down_revision = "011cabf3aef0"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("facet", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.UnicodeText(), nullable=True))

    with op.batch_alter_table("investigativequestion", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.UnicodeText(), nullable=True))

    with op.batch_alter_table("scenario", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.UnicodeText(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenario", schema=None) as batch_op:
        batch_op.drop_column("uuid")

    with op.batch_alter_table("investigativequestion", schema=None) as batch_op:
        batch_op.drop_column("uuid")

    with op.batch_alter_table("facet", schema=None) as batch_op:
        batch_op.drop_column("uuid")

    # ### end Alembic commands ###
