<!--
Copyright 2025 Google Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<template>
  <section>
    <header class="pb-8 mb-8 border-b-thin">
      <h2 class="mb-4 text-h3 font-weight-bold">Investigation Report</h2>

      <div class="d-flex align-center justify-space-between">
        <v-chip size="x-small" variant="outlined" class="px-2 py-2 rounded-l">
          Pre-generated by AI
        </v-chip>
        <div class="d-flex align-center ga-4">
          <v-btn variant="text" size="small" color="primary">
            <v-icon
              icon="mdi-download-circle-outline"
              class="mr-1"
              left
              small
            />
            Download</v-btn
          >
          <v-btn size="small" color="primary"> Complete investigation</v-btn>
        </div>
      </div>
    </header>

    <form>
      <div class="d-flex align-center ga-4">
        <label for="summary" class="font-weight-bold">Name</label>
        <v-text-field
          id="name"
          name="name"
          variant="outlined"
          density="compact"
        ></v-text-field>
      </div>
      <div class="d-flex align-center ga-4">
        <label for="Analyst" class="font-weight-bold">Analyst(s)</label>
        <v-text-field
          id="analyst"
          name="analyst"
          variant="outlined"
          density="compact"
        ></v-text-field>
      </div>
      <div class="d-flex align-center ga-4">
        <p class="font-weight-bold">Finalized Date & Time</p>
        <p>It will be automatically recorded upon completion.</p>
      </div>
      <div class="d-flex align-center ga-4 mb-10">
        <p class="font-weight-bold">Progress</p>
        <p>
          {{ completedQuestionsTotal }} / {{ questionsTotal }} questions
          finalized
        </p>
      </div>

      <div class="mb-8">
        <label for="summary" class="text-h6 font-weight-bold mb-2 d-block"
          >Summary</label
        >
        <v-textarea id="summary" name="summary" variant="outlined"></v-textarea>
      </div>
    </form>

    <div>
      <h3 class="mb-2">Key Findings</h3>
      <ol class="questions-list">
        <li v-for="(question, index) in questions" class="question mb-8">
          <v-icon
            icon="mdi-check-circle"
            v-if="question.conclusions && question.conclusions.length > 0"
            small
            color="#34A853"
          />
          <p class="text-h5 font-weight-medium">{{index + 1}}. {{ question.name }}</p>
          <ul
            class="mt-4 ml-4"
            v-if="question.conclusions && question.conclusions.length > 0"
          >
            <li v-for="conclusion in question.conclusions">
              <p>{{ conclusion.conclusion }}</p>
            </li>
          </ul>
        </li>
      </ol>
    </div>
  </section>
</template>

<script setup>
const { completedQuestionsTotal, questionsTotal, questions } = defineProps({
  questions: Array,
  questionsTotal: Number,
  completedQuestionsTotal: Number,
});
</script>

<style scoped>
.questions-list {
    list-style: none;
}

.question::marker {
  font-size: inherit;
  font-weight: inherit;
}
</style>
