# -*- coding: utf-8 -*-
# Auto generated by Django migrate
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0004_accesscontrolentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrolentry',
            name='user',
            field=models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
    ]
