# -*- coding: utf-8 -*-
# Auto generated by Django migrate
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0008_auto_20140921_1700'),
        ('sketch', '0008_auto_20140921_2137'),
    ]

    operations = [
    ]
