name: build-image

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-timesketch-image:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
  
     - name: Build Docker image
       uses: docker/build-push-action@v4
       with:
          context: docker/release/build
          build-args: |
            BRANCH=${{ github.head_ref }}
