name: build-image

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-timesketch-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Timesketch Docker image
        uses: docker/build-push-action@v4
        with:
          context: docker/release/build
          build-args: |
            BRANCH=${{ github.head_ref }}

      - name: Build Jupyter Labs Docker image
        uses: docker/build-push-action@v4
        with:
          context: docker/dev/build
          file: docker/dev/build/Dockerfile-notebook
          build-args: |
            BRANCH=${{ github.head_ref }}
          build-contexts: timesketch_api_client=api_client/
