name: Cancel
on:
  workflow_run:
    workflows: ["end-to-end", "linter", "unit-tests"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.8.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
