name: eslint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./timesketch/frontend
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: ["12"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn add eslint@5.16.0
      - name: Run eslint
        run: |
          git config pull.rebase false && git fetch -p origin master
          for FILE in `git --no-pager diff origin/master --name-only --diff-filter=ACMR | grep -e \.vue$ -e \.js$ | grep -v dist\/js | sed s/'^timesketch\/frontend\/'/''/`; do echo "Running eslint against ${FILE}"; yarn run eslint ${FILE}; done
