name: unit-tests-frontend

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  yarn:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [ubuntu-22.04]
        node-version: ['10', '12']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: apt install yarn
    - name: Run unit tests with yarn
      run: yarn run --cwd=timesketch/frontend test:unit
